### ISSUE TITLE
LocalDateTime数据类型报错java.lang.StackOverflowError

### ISSUE THREAD

**Issue by wv1124** [apache/dubbo-js#204]
java.lang.StackOverflowError
	at com.alibaba.com.caucho.hessian.io.SerializerFactory.getSerializer(SerializerFactory.java:159)
	at com.alibaba.com.caucho.hessian.io.Hessian2Output.writeObject(Hessian2Output.java:406)
	at com.alibaba.com.caucho.hessian.io.JavaSerializer.writeObject(JavaSerializer.java:203)
	at com.alibaba.com.caucho.hessian.io.Hessian2Output.writeObject(Hessian2Output.java:408)
        .....

感觉是Hessian本身有问题吧

**Comment by binlaniua** [comment]
升级dubbo到2.5.6以上
[ 修改列表 ](https://github.com/apache/dubbo/pull/131)
[ 合并说明 ](https://github.com/apache/dubbo/issues/722)

**Comment by wv1124** [comment]
确认是dubbo问题，不是dubbo2js问题
