### ISSUE TITLE
Can not be find any agents

### ISSUE THREAD

**Issue by h1orz** [apache/dubbo-js#243]
仅初始化Dubbo时，报错。
立刻发起接口调用，不会报错。
有方法仅connect zookeeper吗？或者我用法不对...
目的是调用dubbo接口。

Log:
```
[2021-06-22T14:54:31.886] [INFO] default - onTrace {
  time: '2021-06-22T06:54:31.886Z',
  pid: 20404,
  host: '192.168.146.1',
  type: 'INFO',
  msg: 'dubbo:bootstrap version => 3.0.0-rc6'
}
[2021-06-22T14:54:31.923] [INFO] default - dubbo was ready...
[2021-06-22T14:54:31.924] [INFO] default - onTrace {
  time: '2021-06-22T06:54:31.923Z',
  pid: 20404,
  host: '192.168.146.1',
  type: 'ERR',
  msg: ScheduleError: Can not be find any agents
      at Object.Scheduler._handleZkClientOnData [as onData] (D:\Git\img\node_modules\apache-dubbo-js\es7\scheduler.js:69:29)
      at ZkRegistry._init (D:\Git\img\node_modules\apache-dubbo-js\es7\registry\zookeeper.js:81:30)
      at Client.<anonymous> (D:\Git\img\node_modules\apache-dubbo-js\es7\registry\zookeeper.js:113:17)
      at Object.onceWrapper (events.js:481:28)
      at Client.emit (events.js:375:28)
      at Client.defaultStateListener (D:\Git\img\node_modules\node-zookeeper-client\index.js:55:14)
      at Client.emit (events.js:375:28)
      at Client.onConnectionManagerState (D:\Git\img\node_modules\node-zookeeper-client\index.js:262:14)
      at ConnectionManager.emit (events.js:375:28)
      at ConnectionManager.setState (D:\Git\img\node_modules\node-zookeeper-client\lib\ConnectionManager.js:168:14)
}
```
Code:
```JS
import { Dubbo, java, setting } from 'apache-dubbo-js'

const interfaceName = 'com.xxx.authcenter.facade.service.user.UserServiceFacade'
const interfaceVersion = '1.0.0'
const dubbo = new Dubbo({
  application: {
    name: 'node'
  },
  register: '172.22.7.169:2181',
  dubboVersion: '2.7.6',
  dubboSetting: setting
    .match(interfaceName, {
      version: interfaceVersion
    })
})

dubbo.subscribe({
  onTrace(msg) {
    console.log('onTrace', msg)
  }
});

(async () => {
  await dubbo.ready()
  console.log('dubbo was ready...')
})()

/* 立即请求可以正常连接zookeeper
dubbo.proxyService({
  dubboInterface: interfaceName,
  methods: {
    getUserSession(who) {
      return [java.String(who)]
    }
  }
}).getUserSession('Hain').then(dubboRes => {
  console.log('dubbo1.then', dubboRes)
}).catch(err => {
  console.error('dubbo1.catch', err)
})
*/

```

**Comment by hufeng** [comment]
You can check zookeeper to determine whether the service is registered successfully

**Comment by h1orz** [comment]
> You can check zookeeper to determine whether the service is registered successfully

不明白为何要检查服务是否注册成功，我的目的仅仅是连接zookeeper并查询接口。
使用node-zookeeper-client连接和调用getChildren都没问题。

**Comment by hufeng** [comment]
node启动的时候，加上DEBUG=dubbo* 可以看到全链路的跟踪日志，应该可以找到原因
